### ISSUE TITLE
function putUnitMiningWithDefaultSettings(match, player_index, x, y) issue

### ISSUE THREAD

**Issue by marcu805** [KatekovAnton/MAXTouch-docs#8]
Hello, 

_Coding/editing process_

This function operates different in v10 comparative to v11. I mean the match starts with mining station turned on in v10, but in v11, with same file, same function, the match starts with the station turned off.

When I do not use this function and do not add resources under the station, it works fine in both versions. The match starts with mining station turned on, but no resources to mine. It is just turned on. 0/0 raw 0/0 fuel 0/0 gold. My intention is that the station to be fully operative, but only in v10 it works fine. 

In v11, I must add that after I click "start", it starts, and works ok. Only that it has to be turned on by player, comparative to v10.

Please assist in this matter,

Thank you!

**Comment by KatekovAnton** [comment]
@marcu805  please show me script file

**Comment by KatekovAnton** [comment]
The script file you gave me:
[testMatch.lua.zip](https://github.com/KatekovAnton/MAXTouch-docs/files/3991297/testMatch.lua.zip)

You setup resources in `testMatchLogic:onMatchLoaded ` on this phase all mining station are already initialized and they have only default resources under them.

Instead of it you should setup them inside of `testMatchLogic:onMapLoaded ` as described here:
https://github.com/KatekovAnton/MAXTouch-docs/blob/master/API/GudeForInitializationScript.md#Map-loaded

Just moving your resource creation code should help.

**Comment by KatekovAnton** [comment]
2 more issues

here is the fixed code:
```
function testMatchLogic:onMatchPrepared(game, match)

    local generator = match:playerAtIndex(1):createUnit(10, 46, 'powergen')
    generator:placeUnitOnMap(false)

    local unit_mining = match:playerAtIndex(1):createUnit(11, 45, 'mining')
    unit_mining:setParameterValue(UNIT_PARAMETER_TYPE_MATERIAL, unit_mining:getParameterMaxValue(UNIT_PARAMETER_TYPE_MATERIAL))
    unit_mining:placeUnitOnMap(false)
    unit_mining:turnOn()
``` 

1.  you should  create power generator before mining station - otherwise it will not be able to start
2. you should first place building on the map (it will connect to other buildings) and then turn it on

**Comment by marcu805** [comment]
OK, Thank you...it works ok now.

I knew that some buildings have to be put first in order that others to be active. I've used this function relative recently. Now I keep this in mind and be cautious, when I add units/building on the map.

I met this issue also on units interaction. Some things depend on the order in the script

thanks again!
